# This is a privileged pod that can be used to test runtime findings in Amazon GuardDuty
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: claudioacquaviva/ubuntu-awscli:0.1
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
