apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service
  namespace: team-riker
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  type: NodePort
  selector:
    app: sampleapp
