apiVersion: v1
kind: Pod
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  containers:
  - image: claudioacquaviva/sampleapp
    imagePullPolicy: IfNotPresent
    name: sampleapp
  restartPolicy: Never