apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: claudioacquaviva/sampleapp
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Never